/**
 * World_of_Stories-Api
 * Interactive stories application for NodeJs typescript server
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { RequestDeleteChapter } from '../model/requestDeleteChapter';
import { RequestDeleteNpc } from '../model/requestDeleteNpc';
import { RequestGetChapter } from '../model/requestGetChapter';
import { RequestGetChapters } from '../model/requestGetChapters';
import { RequestGetNpc } from '../model/requestGetNpc';
import { RequestGetNpcs } from '../model/requestGetNpcs';
import { RequestNewNpc } from '../model/requestNewNpc';
import { RequestPublishChapter } from '../model/requestPublishChapter';
import { RequestPublishNpc } from '../model/requestPublishNpc';
import { RequestUpdateChapter } from '../model/requestUpdateChapter';
import { RequestUpdateNpc } from '../model/requestUpdateNpc';
import { ResponseData } from '../model/responseData';
import { ResponseDeleteChapter } from '../model/responseDeleteChapter';
import { ResponseDeleteNpc } from '../model/responseDeleteNpc';
import { ResponseGetChapter } from '../model/responseGetChapter';
import { ResponseGetChapters } from '../model/responseGetChapters';
import { ResponseGetNpc } from '../model/responseGetNpc';
import { ResponseGetNpcs } from '../model/responseGetNpcs';
import { ResponseNewNpc } from '../model/responseNewNpc';
import { ResponsePublishChapter } from '../model/responsePublishChapter';
import { ResponsePublishNpc } from '../model/responsePublishNpc';
import { ResponseUpdateChapter } from '../model/responseUpdateChapter';
import { ResponseUpdateNpc } from '../model/responseUpdateNpc';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class StoriesService {

    protected basePath = 'http://192.168.0.8:3000';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Delete a Chapter
     * Delete a Chapter, it will delete de option pointer to this chapter too
     * @param data Transaction details
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteChapter(data: RequestDeleteChapter, observe?: 'body', reportProgress?: boolean): Observable<ResponseDeleteChapter>;
    public deleteChapter(data: RequestDeleteChapter, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseDeleteChapter>>;
    public deleteChapter(data: RequestDeleteChapter, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseDeleteChapter>>;
    public deleteChapter(data: RequestDeleteChapter, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (data === null || data === undefined) {
            throw new Error('Required parameter data was null or undefined when calling deleteChapter.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ResponseDeleteChapter>(`${this.basePath}/chapters/delete`,
            data,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete a NPC
     * Delete a NPC
     * @param data Transaction details
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteNpc(data: RequestDeleteNpc, observe?: 'body', reportProgress?: boolean): Observable<ResponseDeleteNpc>;
    public deleteNpc(data: RequestDeleteNpc, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseDeleteNpc>>;
    public deleteNpc(data: RequestDeleteNpc, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseDeleteNpc>>;
    public deleteNpc(data: RequestDeleteNpc, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (data === null || data === undefined) {
            throw new Error('Required parameter data was null or undefined when calling deleteNpc.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ResponseDeleteNpc>(`${this.basePath}/npcs/delete`,
            data,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Chapter
     * Get complete Chapter
     * @param data Transaction details
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getChapter(data: RequestGetChapter, observe?: 'body', reportProgress?: boolean): Observable<ResponseGetChapter>;
    public getChapter(data: RequestGetChapter, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseGetChapter>>;
    public getChapter(data: RequestGetChapter, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseGetChapter>>;
    public getChapter(data: RequestGetChapter, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (data === null || data === undefined) {
            throw new Error('Required parameter data was null or undefined when calling getChapter.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ResponseGetChapter>(`${this.basePath}/chapters/chapter`,
            data,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Chapters
     * Get all Chapters of an Npc, filtering by publish status
     * @param data Transaction details
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getChapters(data: RequestGetChapters, observe?: 'body', reportProgress?: boolean): Observable<ResponseGetChapters>;
    public getChapters(data: RequestGetChapters, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseGetChapters>>;
    public getChapters(data: RequestGetChapters, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseGetChapters>>;
    public getChapters(data: RequestGetChapters, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (data === null || data === undefined) {
            throw new Error('Required parameter data was null or undefined when calling getChapters.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ResponseGetChapters>(`${this.basePath}/chapters`,
            data,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get NPC
     * Get complete info of one NPC
     * @param data Transaction details
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getNpc(data: RequestGetNpc, observe?: 'body', reportProgress?: boolean): Observable<ResponseGetNpc>;
    public getNpc(data: RequestGetNpc, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseGetNpc>>;
    public getNpc(data: RequestGetNpc, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseGetNpc>>;
    public getNpc(data: RequestGetNpc, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (data === null || data === undefined) {
            throw new Error('Required parameter data was null or undefined when calling getNpc.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ResponseGetNpc>(`${this.basePath}/npcs/npc`,
            data,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get NPCs
     * Get all NPC in array of IDs, filtering by publish status
     * @param data Transaction details
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getNpcs(data: RequestGetNpcs, observe?: 'body', reportProgress?: boolean): Observable<ResponseGetNpcs>;
    public getNpcs(data: RequestGetNpcs, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseGetNpcs>>;
    public getNpcs(data: RequestGetNpcs, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseGetNpcs>>;
    public getNpcs(data: RequestGetNpcs, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (data === null || data === undefined) {
            throw new Error('Required parameter data was null or undefined when calling getNpcs.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ResponseGetNpcs>(`${this.basePath}/npcs`,
            data,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Add new NPC
     * Add new NPC
     * @param data Transaction details
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public newNpc(data: RequestNewNpc, observe?: 'body', reportProgress?: boolean): Observable<ResponseNewNpc>;
    public newNpc(data: RequestNewNpc, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseNewNpc>>;
    public newNpc(data: RequestNewNpc, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseNewNpc>>;
    public newNpc(data: RequestNewNpc, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (data === null || data === undefined) {
            throw new Error('Required parameter data was null or undefined when calling newNpc.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ResponseNewNpc>(`${this.basePath}/npcs/new`,
            data,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Publish a Chapter
     * Publish the Chapter content to readers
     * @param data Transaction details
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public publishChapter(data: RequestPublishChapter, observe?: 'body', reportProgress?: boolean): Observable<ResponsePublishChapter>;
    public publishChapter(data: RequestPublishChapter, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponsePublishChapter>>;
    public publishChapter(data: RequestPublishChapter, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponsePublishChapter>>;
    public publishChapter(data: RequestPublishChapter, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (data === null || data === undefined) {
            throw new Error('Required parameter data was null or undefined when calling publishChapter.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ResponsePublishChapter>(`${this.basePath}/chapters/publish`,
            data,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Publish a Npc
     * Publish the Npc content to readers
     * @param data Transaction details
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public publishNpc(data: RequestPublishNpc, observe?: 'body', reportProgress?: boolean): Observable<ResponsePublishNpc>;
    public publishNpc(data: RequestPublishNpc, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponsePublishNpc>>;
    public publishNpc(data: RequestPublishNpc, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponsePublishNpc>>;
    public publishNpc(data: RequestPublishNpc, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (data === null || data === undefined) {
            throw new Error('Required parameter data was null or undefined when calling publishNpc.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ResponsePublishNpc>(`${this.basePath}/npcs/publish`,
            data,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update Chapter
     * Update Chapter information
     * @param data Transaction details
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateChapter(data: RequestUpdateChapter, observe?: 'body', reportProgress?: boolean): Observable<ResponseUpdateChapter>;
    public updateChapter(data: RequestUpdateChapter, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseUpdateChapter>>;
    public updateChapter(data: RequestUpdateChapter, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseUpdateChapter>>;
    public updateChapter(data: RequestUpdateChapter, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (data === null || data === undefined) {
            throw new Error('Required parameter data was null or undefined when calling updateChapter.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ResponseUpdateChapter>(`${this.basePath}/chapters/update`,
            data,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update NPC
     * Update NPC
     * @param data Transaction details
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateNpc(data: RequestUpdateNpc, observe?: 'body', reportProgress?: boolean): Observable<ResponseUpdateNpc>;
    public updateNpc(data: RequestUpdateNpc, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseUpdateNpc>>;
    public updateNpc(data: RequestUpdateNpc, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseUpdateNpc>>;
    public updateNpc(data: RequestUpdateNpc, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (data === null || data === undefined) {
            throw new Error('Required parameter data was null or undefined when calling updateNpc.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ResponseUpdateNpc>(`${this.basePath}/npcs/update`,
            data,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
