/**
 * @fileoverview added by tsickle
 * Generated from: model/requestNewCityTravel.ts
 * @suppress {checkTypes,constantProperty,extraRequire,missingOverride,missingRequire,missingReturn,unusedPrivateMembers,uselessCode} checked by tsc
 */
/**
 * World_of_Stories-Api
 * Interactive stories application for NodeJs typescript server
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * @record
 */
export function RequestNewCityTravel() { }
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicmVxdWVzdE5ld0NpdHlUcmF2ZWwuanMiLCJzb3VyY2VSb290Ijoibmc6Ly93b3MtYXBpLyIsInNvdXJjZXMiOlsibW9kZWwvcmVxdWVzdE5ld0NpdHlUcmF2ZWwudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQWFBLDBDQUNDIiwic291cmNlc0NvbnRlbnQiOlsiLyoqXG4gKiBXb3JsZF9vZl9TdG9yaWVzLUFwaVxuICogSW50ZXJhY3RpdmUgc3RvcmllcyBhcHBsaWNhdGlvbiBmb3IgTm9kZUpzIHR5cGVzY3JpcHQgc2VydmVyXG4gKlxuICogT3BlbkFQSSBzcGVjIHZlcnNpb246IDEuMC4wXG4gKiBcbiAqXG4gKiBOT1RFOiBUaGlzIGNsYXNzIGlzIGF1dG8gZ2VuZXJhdGVkIGJ5IHRoZSBzd2FnZ2VyIGNvZGUgZ2VuZXJhdG9yIHByb2dyYW0uXG4gKiBodHRwczovL2dpdGh1Yi5jb20vc3dhZ2dlci1hcGkvc3dhZ2dlci1jb2RlZ2VuLmdpdFxuICogRG8gbm90IGVkaXQgdGhlIGNsYXNzIG1hbnVhbGx5LlxuICovXG5cblxuZXhwb3J0IGludGVyZmFjZSBSZXF1ZXN0TmV3Q2l0eVRyYXZlbCB7IFxufVxuIl19