/**
 * @fileoverview added by tsickle
 * Generated from: model/requestRemoveCityDescription.ts
 * @suppress {checkTypes,constantProperty,extraRequire,missingOverride,missingRequire,missingReturn,unusedPrivateMembers,uselessCode} checked by tsc
 */
/**
 * World_of_Stories-Api
 * Interactive stories application for NodeJs typescript server
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * @record
 */
export function RequestRemoveCityDescription() { }
if (false) {
    /** @type {?|undefined} */
    RequestRemoveCityDescription.prototype.descriptionId;
}
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicmVxdWVzdFJlbW92ZUNpdHlEZXNjcmlwdGlvbi5qcyIsInNvdXJjZVJvb3QiOiJuZzovL3dvcy1hcGkvIiwic291cmNlcyI6WyJtb2RlbC9yZXF1ZXN0UmVtb3ZlQ2l0eURlc2NyaXB0aW9uLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUFhQSxrREFFQzs7O0lBREcscURBQXVCIiwic291cmNlc0NvbnRlbnQiOlsiLyoqXG4gKiBXb3JsZF9vZl9TdG9yaWVzLUFwaVxuICogSW50ZXJhY3RpdmUgc3RvcmllcyBhcHBsaWNhdGlvbiBmb3IgTm9kZUpzIHR5cGVzY3JpcHQgc2VydmVyXG4gKlxuICogT3BlbkFQSSBzcGVjIHZlcnNpb246IDEuMC4wXG4gKiBcbiAqXG4gKiBOT1RFOiBUaGlzIGNsYXNzIGlzIGF1dG8gZ2VuZXJhdGVkIGJ5IHRoZSBzd2FnZ2VyIGNvZGUgZ2VuZXJhdG9yIHByb2dyYW0uXG4gKiBodHRwczovL2dpdGh1Yi5jb20vc3dhZ2dlci1hcGkvc3dhZ2dlci1jb2RlZ2VuLmdpdFxuICogRG8gbm90IGVkaXQgdGhlIGNsYXNzIG1hbnVhbGx5LlxuICovXG5cblxuZXhwb3J0IGludGVyZmFjZSBSZXF1ZXN0UmVtb3ZlQ2l0eURlc2NyaXB0aW9uIHsgXG4gICAgZGVzY3JpcHRpb25JZD86IHN0cmluZztcbn1cbiJdfQ==