/**
 * @fileoverview added by tsickle
 * Generated from: model/requestRemovePlaceEntry.ts
 * @suppress {checkTypes,constantProperty,extraRequire,missingOverride,missingRequire,missingReturn,unusedPrivateMembers,uselessCode} checked by tsc
 */
/**
 * World_of_Stories-Api
 * Interactive stories application for NodeJs typescript server
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * @record
 */
export function RequestRemovePlaceEntry() { }
if (false) {
    /** @type {?|undefined} */
    RequestRemovePlaceEntry.prototype.entryId;
}
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicmVxdWVzdFJlbW92ZVBsYWNlRW50cnkuanMiLCJzb3VyY2VSb290Ijoibmc6Ly93b3MtYXBpLyIsInNvdXJjZXMiOlsibW9kZWwvcmVxdWVzdFJlbW92ZVBsYWNlRW50cnkudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQWFBLDZDQUVDOzs7SUFERywwQ0FBaUIiLCJzb3VyY2VzQ29udGVudCI6WyIvKipcbiAqIFdvcmxkX29mX1N0b3JpZXMtQXBpXG4gKiBJbnRlcmFjdGl2ZSBzdG9yaWVzIGFwcGxpY2F0aW9uIGZvciBOb2RlSnMgdHlwZXNjcmlwdCBzZXJ2ZXJcbiAqXG4gKiBPcGVuQVBJIHNwZWMgdmVyc2lvbjogMS4wLjBcbiAqIFxuICpcbiAqIE5PVEU6IFRoaXMgY2xhc3MgaXMgYXV0byBnZW5lcmF0ZWQgYnkgdGhlIHN3YWdnZXIgY29kZSBnZW5lcmF0b3IgcHJvZ3JhbS5cbiAqIGh0dHBzOi8vZ2l0aHViLmNvbS9zd2FnZ2VyLWFwaS9zd2FnZ2VyLWNvZGVnZW4uZ2l0XG4gKiBEbyBub3QgZWRpdCB0aGUgY2xhc3MgbWFudWFsbHkuXG4gKi9cblxuXG5leHBvcnQgaW50ZXJmYWNlIFJlcXVlc3RSZW1vdmVQbGFjZUVudHJ5IHsgXG4gICAgZW50cnlJZD86IHN0cmluZztcbn1cbiJdfQ==