/**
 * @fileoverview added by tsickle
 * Generated from: model/requestGetUser.ts
 * @suppress {checkTypes,constantProperty,extraRequire,missingOverride,missingRequire,missingReturn,unusedPrivateMembers,uselessCode} checked by tsc
 */
/**
 * World_of_Stories-Api
 * Interactive stories application for NodeJs typescript server
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * @record
 */
export function RequestGetUser() { }
if (false) {
    /** @type {?|undefined} */
    RequestGetUser.prototype.id;
}
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicmVxdWVzdEdldFVzZXIuanMiLCJzb3VyY2VSb290Ijoibmc6Ly93b3MtYXBpLyIsInNvdXJjZXMiOlsibW9kZWwvcmVxdWVzdEdldFVzZXIudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQWFBLG9DQUVDOzs7SUFERyw0QkFBWSIsInNvdXJjZXNDb250ZW50IjpbIi8qKlxuICogV29ybGRfb2ZfU3Rvcmllcy1BcGlcbiAqIEludGVyYWN0aXZlIHN0b3JpZXMgYXBwbGljYXRpb24gZm9yIE5vZGVKcyB0eXBlc2NyaXB0IHNlcnZlclxuICpcbiAqIE9wZW5BUEkgc3BlYyB2ZXJzaW9uOiAxLjAuMFxuICogXG4gKlxuICogTk9URTogVGhpcyBjbGFzcyBpcyBhdXRvIGdlbmVyYXRlZCBieSB0aGUgc3dhZ2dlciBjb2RlIGdlbmVyYXRvciBwcm9ncmFtLlxuICogaHR0cHM6Ly9naXRodWIuY29tL3N3YWdnZXItYXBpL3N3YWdnZXItY29kZWdlbi5naXRcbiAqIERvIG5vdCBlZGl0IHRoZSBjbGFzcyBtYW51YWxseS5cbiAqL1xuXG5cbmV4cG9ydCBpbnRlcmZhY2UgUmVxdWVzdEdldFVzZXIgeyBcbiAgICBpZD86IHN0cmluZztcbn1cbiJdfQ==