/**
 * @fileoverview added by tsickle
 * Generated from: model/requestSetRol.ts
 * @suppress {checkTypes,constantProperty,extraRequire,missingOverride,missingRequire,missingReturn,unusedPrivateMembers,uselessCode} checked by tsc
 */
/**
 * World_of_Stories-Api
 * Interactive stories application for NodeJs typescript server
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * @record
 */
export function RequestSetRol() { }
if (false) {
    /** @type {?|undefined} */
    RequestSetRol.prototype.id;
    /** @type {?|undefined} */
    RequestSetRol.prototype.rol;
}
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicmVxdWVzdFNldFJvbC5qcyIsInNvdXJjZVJvb3QiOiJuZzovL3dvcy1hcGkvIiwic291cmNlcyI6WyJtb2RlbC9yZXF1ZXN0U2V0Um9sLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUFhQSxtQ0FHQzs7O0lBRkcsMkJBQVk7O0lBQ1osNEJBQWEiLCJzb3VyY2VzQ29udGVudCI6WyIvKipcbiAqIFdvcmxkX29mX1N0b3JpZXMtQXBpXG4gKiBJbnRlcmFjdGl2ZSBzdG9yaWVzIGFwcGxpY2F0aW9uIGZvciBOb2RlSnMgdHlwZXNjcmlwdCBzZXJ2ZXJcbiAqXG4gKiBPcGVuQVBJIHNwZWMgdmVyc2lvbjogMS4wLjBcbiAqIFxuICpcbiAqIE5PVEU6IFRoaXMgY2xhc3MgaXMgYXV0byBnZW5lcmF0ZWQgYnkgdGhlIHN3YWdnZXIgY29kZSBnZW5lcmF0b3IgcHJvZ3JhbS5cbiAqIGh0dHBzOi8vZ2l0aHViLmNvbS9zd2FnZ2VyLWFwaS9zd2FnZ2VyLWNvZGVnZW4uZ2l0XG4gKiBEbyBub3QgZWRpdCB0aGUgY2xhc3MgbWFudWFsbHkuXG4gKi9cblxuXG5leHBvcnQgaW50ZXJmYWNlIFJlcXVlc3RTZXRSb2wgeyBcbiAgICBpZD86IHN0cmluZztcbiAgICByb2w/OiBzdHJpbmc7XG59XG4iXX0=